// <auto-generated />
using System;
using ItauCorretora.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItauCorretora.Infrastructure.Migrations
{
    [DbContext(typeof(CompraProgramadaDbContext))]
    partial class CompraProgramadaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ItauCorretora.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensalAporte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("ContasGraficas", (string)null);
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContaGraficaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("CustodiasFilhotes", (string)null);
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("ItauCorretora.Domain.Entities.Cliente", null)
                        .WithOne("ContaGrafica")
                        .HasForeignKey("ItauCorretora.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.HasOne("ItauCorretora.Domain.Entities.ContaGrafica", null)
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica")
                        .IsRequired();
                });

            modelBuilder.Entity("ItauCorretora.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });
#pragma warning restore 612, 618
        }
    }
}
