name: CI/CD Pipeline - Itaú Corretora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Configurar o .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restaurar pacotes
      run: dotnet restore

    - name: Compilar a Solução
      run: dotnet build --no-restore

    - name: Rodar os Testes (xUnit)
      run: dotnet test --no-build --verbosity normal